import discord
from discord.ext import commands


intents = discord.Intents.default()
intents.messages = True
intents.message_content = True
bot = commands.Bot(command_prefix='!', intents=intents)


kufur_listesi = kufur_listesi = ["abaza", "abazan", "ag", "ağzına sıçayım", "ahmak", "allah", "allahsız",
    "am", "amarım", "ambiti", "am biti", "amcığı", "amcığın", "amcığını",
    "amcığınızı", "amcık", "amcık hoşafı", "amcıklama", "amcıklandı", "amcik",
    "amck", "amckl", "amcklama", "amcklaryla", "amckta", "amcktan", "amcuk",
    "amık", "amına", "amınako", "amına koy", "amına koyarım", "amına koyayım",
    "amınakoyim", "amına koyyim", "amına s", "amına sikem", "amına sokam",
    "amın feryadı", "amını", "amını s", "amın oglu", "amınoğlu", "amın oğlu",
    "amısına", "amısını", "amina", "amina g", "amina k", "aminako",
    "aminakoyarim", "amina koyarim", "amina koyayım", "amina koyayim",
    "aminakoyim", "aminda", "amindan", "amindayken", "amini",
    "aminiyarraaniskiim", "aminoglu", "amin oglu", "amiyum", "amk", "amkafa",
    "amk çocuğu", "amlarnzn", "amlı", "amm", "ammak", "ammna", "amn", "amna",
    "amnda", "amndaki", "amngtn", "amnn", "amona", "amq", "amsız", "amsiz",
    "amsz", "amteri", "amugaa", "amuğa", "amuna", "ana", "anaaann", "anal",
    "analarn", "anam", "anamla", "anan", "anana", "anandan", "ananı", "ananı",
    "ananın", "ananın am", "ananın amı", "ananın dölü", "ananınki",
    "ananısikerim", "ananı sikerim", "ananısikeyim", "ananı sikeyim",
    "ananızın", "ananızın am", "anani", "ananin", "ananisikerim",
    "anani sikerim", "ananisikeyim", "anani sikeyim", "anann", "ananz",
    "anas", "anasını", "anasının am", "anası orospu", "anasi", "anasinin",
    "anay", "anayin", "angut", "anneni", "annenin", "annesiz", "anuna",
    "aptal", "aq", "a.q", "a.q.", "aq.", "ass", "atkafası", "atmık",
    "attırdığım", "attrrm", "auzlu", "avrat", "ayklarmalrmsikerim", "azdım",
    "azdır", "azdırıcı", "babaannesi kaşar", "babanı", "babanın", "babani",
    "babası pezevenk", "bacağına sıçayım", "bacına", "bacını", "bacının",
    "bacini", "bacn", "bacndan", "bacy", "bastard", "basur", "beyinsiz",
    "bızır", "bitch", "biting", "bok", "boka", "bokbok", "bokça", "bokhu",
    "bokkkumu", "boklar", "boktan", "boku", "bokubokuna", "bokum", "bombok",
    "boner", "bosalmak", "boşalmak", "cenabet", "cibiliyetsiz",
    "cibilliyetini", "cibilliyetsiz", "cif", "cikar", "cim", "çük", "dalaksız",
    "dallama", "daltassak", "dalyarak", "dalyarrak", "dangalak", "dassagi",
    "diktim", "dildo", "dingil", "dingilini", "dinsiz", "dkerim", "domal",
    "domalan", "domaldı", "domaldın", "domalık", "domalıyor", "domalmak",
    "domalmış", "domalsın", "domalt", "domaltarak", "domaltıp", "domaltır",
    "domaltırım", "domaltip", "domaltmak", "dölü", "dönek", "düdük", "eben",
    "ebeni", "ebenin", "ebeninki", "ebleh", "ecdadını", "ecdadini", "embesil", 
    "emi", "fahise", "fahişe", "feriştah", "ferre", "fuck", "fucker", "fuckin", 
    "fucking", "gavad", "gavat", "geber", "geberik", "gebermek", "gebermiş", 
    "gebertir", "gerızekalı", "gerizekalı", "gerizekali", "gerzek", "giberim", 
    "giberler", "gibis", "gibiş", "gibmek", "gibtiler", "goddamn", "godoş", 
    "godumun", "gotelek", "gotlalesi", "gotlu", "gotten", "gotundeki", 
    "gotunden", "gotune", "gotunu", "gotveren", "goyiim", "goyum", "goyuyim", 
    "goyyim", "göt", "göt deliği", "götelek", "göt herif", "götlalesi", "götlek", 
    "götoğlanı", "göt oğlanı", "götoş", "götten", "götü", "götün", "götüne", 
    "götünekoyim", "götüne koyim", "götünü", "götveren", "göt veren", "göt verir", 
    "gtelek", "gtn", "gtnde", "gtnden", "gtne", "gtten", "gtveren", "hasiktir", 
    "hassikome", "hassiktir", "has siktir", "hassittir", "haysiyetsiz", 
    "hayvan herif", "hoşafı", "hödük", "hsktr", "huur", "ıbnelık", "ibina", 
    "ibine", "ibinenin", "ibne", "ibnedir", "ibneleri", "ibnelik", "ibnelri", 
    "ibneni", "ibnenin", "ibnerator", "ibnesi", "idiot", "idiyot", "imansz", 
    "ipne", "iserim", "işerim", "itoğlu it", "kafam girsin", "kafasız", "kafasiz", 
    "kahpe", "kahpenin", "kahpenin feryadı", "kaka", "kaltak", "kancık", "kancik", 
    "kappe", "karhane", "kaşar", "kavat", "kavatn", "kaypak", "kayyum", "kerane", 
    "kerhane", "kerhanelerde", "kevase", "kevaşe", "kevvase", "koca göt", 
    "koduğmun", "koduğmunun", "kodumun", "kodumunun", "koduumun", "koyarm", 
    "koyayım", "koyiim", "koyiiym", "koyim", "koyum", "koyyim", "krar", 
    "kukudaym", "laciye boyadım", "lavuk", "liboş", "madafaka", "mal", "malafat", 
    "malak", "manyak", "mcik", "meme", "memelerini", "mezveleli", "minaamcık", 
    "mincikliyim", "mna", "monakkoluyum", "motherfucker", "mudik", "oc", "ocuu", 
    "ocuun", "OÇ", "oç", "o. çocuğu", "oğlan", "oğlancı", "oğlu it","orosbucocuu",
    "orospu", "orospucocugu", "orospu cocugu", "orospu çoc",
    "orospuçocuğu", "orospu çocuğu", "orospu çocuğudur", "orospu çocukları",
    "orospudur", "orospular", "orospunun", "orospunun evladı", "orospuydu",
    "orospuyuz", "orostoban", "orostopol", "orrospu", "oruspu", "oruspuçocuğu",
    "oruspu çocuğu", "osbir", "ossurduum", "ossurmak", "ossuruk", "osur",
    "osurduu", "osuruk", "osururum", "otuzbir", "öküz", "öşex", "patlak zar",
    "penis", "pezevek", "pezeven", "pezeveng", "pezevengi", "pezevengin evladı",
    "pezevenk", "pezo", "pic", "pici", "picler", "piç", "piçin oğlu",
    "piç kurusu", "piçler", "pipi", "pipiş", "pisliktir", "porno", "pussy",
    "puşt", "puşttur", "rahminde", "revizyonist", "s1kerim", "s1kerm", "s1krm",
    "sakso", "saksofon", "salaak", "salak", "saxo", "sekis", "serefsiz",
    "sevgi koyarım", "sevişelim", "sexs", "sıçarım", "sıçtığım", "sıecem",
    "sicarsin", "sie", "sik", "sikdi", "sikdiğim", "sike", "sikecem", "sikem",
    "siken", "sikenin", "siker", "sikerim", "sikerler", "sikersin", "sikertir",
    "sikertmek", "sikesen", "sikesicenin", "sikey", "sikeydim", "sikeyim",
    "sikeym", "siki", "sikicem", "sikici", "sikien", "sikienler", "sikiiim",
    "sikiiimmm", "sikiim", "sikiir", "sikiirken", "sikik", "sikil", "sikildiini",
    "sikilesice", "sikilmi", "sikilmie", "sikilmis", "sikilmiş", "sikilsin",
    "sikim", "sikimde", "sikimden", "sikime", "sikimi", "sikimiin", "sikimin",
    "sikimle", "sikimsonik", "sikimtrak", "sikin", "sikinde", "sikinden",
    "sikine", "sikini", "sikip", "sikis", "sikisek", "sikisen", "sikish",
    "sikismis", "sikiş", "sikişen", "sikişme", "sikitiin", "sikiyim", "sikiym",
    "sikiyorum", "sikkim", "sikko", "sikleri", "sikleriii", "sikli", "sikm",
    "sikmek", "sikmem", "sikmiler", "sikmisligim", "siksem", "sikseydin",
    "sikseyidin", "siksin", "siksinbaya", "siksinler", "siksiz", "siksok",
    "siksz", "sikt", "sikti", "siktigimin", "siktigiminin", "siktiğim",
    "siktiğimin", "siktiğiminin", "siktii", "siktiim", "siktiimin", "siktiiminin",
    "siktiler", "siktim", "siktimin", "siktiminin", "siktir", "siktir et",
    "siktirgit", "siktir git", "siktirir", "siktiririm", "siktiriyor",
    "siktir lan", "siktirolgit", "siktir ol git", "sittimin", "sittir", "skcem",
    "skecem", "skem", "sker", "skerim", "skerm", "skeyim", "skiim", "skik",
    "skim", "skime", "skmek", "sksin", "sksn", "sksz", "sktiimin", "sktrr",
    "skyim", "slaleni", "sokam", "sokarım", "sokarim", "sokarm", "sokarmkoduumun",
    "sokayım", "sokaym", "sokiim", "soktuğumunun", "sokuk", "sokum", "sokuş",
    "sokuyum", "soxum", "sulaleni", "sülaleni", "sülalenizi", "sürtük",
    "şerefsiz", "şıllık", "taaklarn", "taaklarna", "tarrakimin", "tasak", "tassak",
    "taşak", "taşşak", "tipini s.k", "tipinizi s.keyim", "tiyniyat", "toplarm",
    "topsun", "totoş", "vajina", "vajinanı", "veled", "veledizina", "veled i zina",
    "verdiimin", "weled", "weledizina", "whore", "xikeyim", "yaaraaa", "yalama",
    "yalarım", "yalarun", "yaraaam", "yarak", "yaraksız", "yaraktr", "yaram",
    "yaraminbasi", "yaramn", "yararmorospunun", "yarra", "yarraaaa", "yarraak",
    "yarraam", "yarraamı", "yarragi", "yarragimi", "yarragina", "yarragindan",
    "yarragm", "yarrağ", "yarrağım", "yarrağımı", "yarraimin", "yarrak", "yarram",
    "yarramin", "yarraminbaşı", "yarramn", "yarran", "yarrana", "yarrrak",
    "yavak", "yavş", "yavşak", "yavşaktır", "yavuşak", "yılışık", "yilisik",
    "yogurtlayam", "yoğurtlayam", "yrrak", "zıkkımım", "zibidi", "zigsin",
    "zikeyim", "zikiiim", "zikiim", "zikik", "zikim", "ziksiiin", "ziksiin",
    "zulliyetini", "zviyetini", "allahını", "amk", "biç", "cocugu", "dasak", "dassak",
    "daşak", "daşşak", "göt", "oc", "oç", "opu", "or", "orlu", "oropu", "orpu", "orsp",
    "sik", "yarak", "yarak kafası", "yarrak", "yavsak", "yavsk", "yavşak", "yrk", "alahnı", 
    "allahını", "allaj", "allajnı", "allanı", "arap peygamber", "beygamber", "isanı", "mahonu", 
    "mihimmid", "muhammed ini", "muhammedini", "muhammetini", "muhonu", "mühimmad", 
    "mühimmat", "mühimmatını", "mühimmatini", "sikeyim", "sikik", "sürtük", "tanrını", 
    "amcktan", "amcuk", "amık", "amın feryadı", "amın oglu", "amın oğlu", "amına", 
    "amına koy", "amına koyarım", "amına koyayım", "amına koyyim", "amına s", 
    "amına sikem", "amına sokam", "amınako", "amınakoyim", "amını", "amını s", 
    "amınoğlu", "amısına", "amısını", "amina", "amina g", "amina k", "aminako","a.q", "a.q.", "amin oglu",
    "amina koyarim", "amina koyayım", "amina koyayim", "aminako", "aminakoyarim", "aminakoyim", "aminda", 
    "amindan", "amindayken", "amini", "aminiyarraaniskiim","aminoglu", "amiyum", "amk", "amk çocuğu", 
    "amkafa", "amlarnzn", "amlı", "amm", "ammak", "ammna", 
    "amn", "amna", "amnda", "amndaki", "amngtn", "amnn", "amona", "amq", "amsız", "amsiz", "amsz", 
    "amteri", "amugaa", "amuğa", "amuna", "ana", "anaaann", "anal", "analarn", "anam", "anamla", "anan", 
    "anana", "anandan", "ananı", "ananı sikerim", "ananı sikeyim", "ananın", "ananın am", "ananın amı", 
    "ananın dölü", "ananınki", "ananısikerim", "ananısikeyim", "ananızın", "ananızın am", "anani", 
    "anani sikerim", "anani sikeyim", "ananin", "ananisikerim", "ananisikeyim", "anann", "ananz", "anas", 
    "anası orospu", "anasını", "anasının am", "anasi", "anasinin", "anay", "anayin", "angut", "anneni", 
    "annenin", "annesiz", "anuna", "aptal", "aq", "aq.", "ass", "atkafası", "atmık", "attırdığım", "attrrm", 
    "auzlu", "avrat", "ayklarmalrmsikerim", "azdım", "azdır", "azdırıcı", "babaannesi kaşar", "babanı", 
    "babanın", "babani", "babası pezevenk", "bacağına sıçayım", "bacına", "bacını", "bacının", "bacini", 
    "bacn", "bacndan", "bacy", "bastard", "basur", "beyinsiz", "bızır", "bitch", "biting", "bok", "boka", 
    "bokbok", "bokça", "bokhu", "bokkkumu", "boklar", "boktan", "boku", "bokubokuna", "bokum", "bombok", 
    "boner", "bosalmak", "boşalmak", "cenabet", "cibiliyetsiz", "cibilliyetini", "cibilliyetsiz", "cif", 
    "cikar", "cim", "çük", "dalaksız", "dallama", "daltassak", "dalyarak", "dalyarrak", "dangalak", "dassagi", 
    "diktim", "dildo", "dingil", "dingilini", "dinsiz", "dkerim", "domal", "domalan", "domaldı", "domaldın", 
    "domalık", "domalıyor", "domalmak", "domalmış", "domalsın", "domalt", "domaltarak", "domaltıp", "domaltır", 
    "domaltırım", "domaltip", "domaltmak", "dölü", "dönek", "düdük", "eben", "ebeni", "ebenin", "ebeninki", 
    "ebleh", "ecdadını", "ecdadini", "embesil", "emi", "fahise", "fahişe", "feriştah", "ferre", "fuck", 
    "fucker", "fuckin", "fucking", "gavad", "gavat", "geber", "geberik", "gebermek", "gebermiş", "gebertir", 
    "gerızekalı", "gerizekalı", "gerizekali", "gerzek", "giberim", "giberler", "gibis", "gibiş", "gibmek", 
    "gibtiler", "goddamn", "godoş", "godumun", "gotelek", "gotlalesi", "gotlu", "gotten", "gotundeki", 
    "gotunden", "gotune", "gotunu", "gotveren", "goyiim", "goyum", "goyuyim", "goyyim", "göt", "göt deliği", 
    "göt herif", "göt oğlanı", "göt veren", "göt verir", "götelek", "götlek", "götoğlanı", "götoş", "götten", 
    "götü", "götün", "götüne", "götüne koyim", "götünekoyim", "götünü", "götveren", "gtelek", "gtn", "gtnde", 
    "gtnden", "gtne", "gtten", "gtveren", "has siktir", "hasiktir", "hassikome", "hassiktir", "hassittir", 
    "haysiyetsiz", "hayvan herif", "hoşafı", "hödük", "hsktr", "huur", "ıbnelık", "ibina", "ibine", "ibinenin", 
    "ibne", "ibnedir", "ibneleri", "ibnelik", "ibnelri", "ibneni", "ibnenin", "ibnerator", "ibnesi", "idiot", 
    "idiyot", "imansz", "ipne", "iserim", "işerim", "itoğlu it", "kafam girsin", "kafasız", "kafasiz", "kahpe", 
    "kahpenin", "kahpenin feryadı", "kaka", "kaltak", "kancık", "kancik", "kappe", "karhane", "kaşar", "kavat", 
    "kavatn", "kaypak", "kayyum", "kerane", "kerhane", "kerhanelerde", "kevase", "kevaşe", "kevveşe", "koca göt", 
    "koduğmun", "koduğmunun", "kodumun", "kodumunun", "koduumun", "koyarm", "koyayım", "koyiim", "koyiiym", 
    "koyim", "koyum", "koyyim", "krar", "kukudaym", "laciye boyadım", "lavuk", "liboş", "madafaka", "mal", 
    "malafat", "malak", "manyak", "mcik", "meme", "memelerini", "mezveleli", "minaamcık", "mincikliyim", "mna", 
    "monakkoluyum", "motherfucker", "mudik", "o. çocuğu", "oc", "ocuu", "ocuun", "oç", "OÇ", "oğlan", "oğlancı", 
    "oğlu it", "orosbucocuu", "orospu", "orospu cocugu", "orospu çoc", "orospu çocuğu", "orospu çocuğudur", 
    "orospu çocukları", "orospucocugu", "orospuçocuğu", "orospudur", "orospular", "orospunun", "orospunun evladı", 
    "orospuydu", "orospuyuz", "orostoban", "orostopol", "orrospu", "oruspu", "oruspu çocuğu", "oruspuçocuğu", 
    "osbir", "ossurduum", "ossurmak", "ossuruk", "osur", "osurduu", "osuruk", "osururum", "otuzbir", "öküz", "öşex", 
    "patlak zar", "penis", "pezevek", "pezeven", "pezeveng", "pezevengi", "pezevengin evladı", "pezevenk", "pezo", 
    "pic", "pici", "picler", "piç", "piç kurusu", "piçin oğlu", "piçler", "pipi", "pipiş", "pisliktir", "porno", 
    "pussy", "puşt", "puşttur", "rahminde", "revizyonist", "s1kerim", "s1kerm", "s1krm", "sakso", "saksofon", 
    "salaak", "salak", "saxo", "sekis", "serefsiz", "sevgi koyarım", "sevişelim", "sexs", "sıçarım", "sıçtığım", 
    "sıecem", "sicarsin", "sie", "sik", "sikdi", "sikdiğim", "sike", "sikecem", "sikem", "siken", "sikenin", 
    "siker", "sikerim", "sikerler", "sikersin", "sikertir", "sikertmek", "sikesen", "sikesicenin", "sikey", 
    "sikeydim", "sikeyim", "sikeym", "siki", "sikicem", "sikici", "sikien", "sikienler", "sikiiim", "sikiiimmm", 
    "sikiim", "sikiir", "sikiirken", "sikik", "sikil", "sikildiini", "sikilesice", "sikilmi", "sikilmie", 
    "sikilmis", "sikilmiş", "sikilsin", "sikim", "sikimde", "sikimden", "sikime", "sikimi", "sikimiin", "sikimin", 
    "sikimle", "sikimsonik", "sikimtrak", "sikin", "sikinde", "sikinden", "sikine", "sikini", "sikip", "sikis", 
    "sikisek", "sikisen", "sikish", "sikismis", "sikiş", "sikişen", "sikişme", "sikitiin", "sikiyim", "sikiym", 
    "sikiyorum", "sikkim", "sikko", "siklerin", "sikleriii", "sikli", "sikm", "sikmek", "sikmem", "sikmiler", 
    "sikmisligim", "siksem", "sikseydin", "sikseyidin", "siksin", "siksinbaya", "siksinler", "siksiz", "siksok", 
    "siksz", "sikt", "sikti", "siktigimin", "siktigiminin", "siktiğim", "siktiğimin", "siktiğiminin", "sikti", 
    "siktiim", "siktiimin", "siktiiminin", "siktiler", "siktim", "siktimin", "siktiminin", "siktir", "siktir et", 
    "siktir git", "siktir lan", "siktir ol git", "siktirgit", "siktirir", "siktiririm", "siktiriyor", "siktirolgit", 
    "sittimin", "sittir", "skcem", "skecem", "skem", "sker", "skerim", "skerm", "skeyim", "skiim", "skik", 
    "skim", "skime", "skmek", "sksin", "sksn", "sksz", "sktiimin", "sktrr", "skyim", "slaleni", "sokam", 
    "sokarım", "sokarim", "sokarm", "sokarmkoduumun", "sokayım", "sokaym", "sokiim", "soktuğumunun", "sokuk", 
    "sokum", "sokuş", "sokuyum", "soxum", "sulaleni", "sülaleni", "sülalenizi", "sürtük", "şerefsiz", "şıllık", 
    "taaklarn", "taaklarna", "tarrakimin", "tasak", "tassak", "taşak", "taşşak", "tipini s.k", "tipinizi s.keyim", 
    "tiyniyat", "toplarm", "topsun", "totoş", "vajina", "vajinanı", "veled", "veled i zina", "veledizina", 
    "verdiimin", "weled", "weledizina", "whore", "xikeyim", "yaaraaa", "yalama", "yalarım", "yalarun", "yaraaam", 
    "yarak", "yaraksız", "yaraktr", "yaram", "yaraminbasi", "yaramn", "yararmorospunun", "yarra", "yarraaaa", 
    "yarraak", "yarraam", "yarraamı", "yarragi", "yarragimi", "yarragina", "yarragindan", "yarragm", "yarrağ", 
    "yarrağım", "yarrağımı", "yarraimin", "yarrak", "yarram", "yarramin", "yarraminbaşı", "yarramn", "yarran", 
    "yarrana", "yarrrak", "yavak", "yavş", "yavşak", "yavşaktır", "yavuşak", "yılışık", "yilisik", "yogurtlayam", 
    "yoğurtlayam", "yrrak", "zıkkımım", "zibidi", "zigsin", "zikeyim", "zikiiim", "zikiim", "zikik", "zikim", 
    "ziksiiin", "ziksiin", "zulliyetini", "zviyetini","ananısikim",]


@bot.event
async def on_ready():
    print(f"Bot {bot.user} aktif!")

@bot.event
async def on_message(message):
    
    if message.author.bot:
        return


    mesaj_kelimeri = message.content.lower().split()
    selamlasma_kelimeri = message.content.lower().split()
    yeni_mesaj = message.content

    for kufur in kufur_listesi:
        if kufur in mesaj_kelimeri:
            yeni_mesaj = yeni_mesaj.replace(kufur, "KÜFÜR VE ARGO KELİME KULLANMAK YASAK!!!") 
    if yeni_mesaj != message.content:
        await message.delete()
        await message.channel.send(f"{message.author.mention} --> {yeni_mesaj}")
    
   
    await bot.process_commands(message)


bot.run('TOKEN')
